[package]
name = "reference_borrowing"
version = "0.1.0"
authors = ["raptazure <1051276278@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
