os: linux
dist: bionic
language: node_js
node_js: 12
install:
  - npm install -g purescript spago
  - wget https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz
  - tar -xzvf mdbook-*.tar.gz
script:
  - travis_fold start "build"
  - ./scripts/buildAll.sh
  - travis_fold end "build"
  - travis_fold start "test"
  - ./scripts/testAll.sh
  - travis_fold end "test"
  - ./mdbook build
  - cp CNAME book/
  - travis_fold start "remove anchors"
  - ./scripts/removeAnchors.sh
  - travis_fold end "remove anchors"
  - travis_fold start "test again"
  - ./scripts/testAll.sh
  - travis_fold end "test again"
  - travis_fold start "reset solutions"
  - ./scripts/resetSolutions.sh
  - travis_fold end "reset solutions"
before_deploy:
  openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
deploy:
  edge: true # use Travis-CI dpl v2
  provider: pages
  local_dir: book
  deploy_key: deploy_key
