[package]
name = "tokio_again"
version = "0.1.0"
authors = ["raptazure <raptazure@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18", features = ["full"] }
