[package]
name = "many_linked_lists"
version = "0.1.0"
authors = ["raptazure <hermit0x9@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
